
---
# Config: clusterrole
# Source: hwameistor/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hwameistor-role
rules:
- apiGroups: ["*"]
  resources:
  - "*"
  verbs: ["*"]
- nonResourceURLs: ["*"]
  verbs: ["*"]

---
# Config: clusterrolebinding
# Source: hwameistor/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hwameistor-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hwameistor-role
subjects:
- kind: ServiceAccount
  name: hwameistor-admin
  namespace: hwameistor-system

---
# Config: serviceaccount
# Source: hwameistor/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hwameistor-admin
  namespace: hwameistor-system

