apiVersion: v1
kind: ConfigMap
metadata:
  name: hwameistor-scheduler-config
  namespace: {{ .Release.Namespace}}
data:
apiVersion: v1
kind: ConfigMap
metadata:
  name: hwameistor-scheduler-config
  namespace: {{ .Release.Namespace }}
data:
  hwameistor-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: hwameistor-scheduler
    leaderElection:
      leaderElect: true
      lockObjectName: hwameistor-scheduler
      resourceLock: leases
    plugins:
      filter:
        enabled:
          - name: hwameistor-scheduler-plugin
      reserve:
        enabled:
          - name: hwameistor-scheduler-plugin
      unreserve:
        enabled:
          - name: hwameistor-scheduler-plugin
